skills = {'Python': {'category': 'programming_language', 'aliases': ['python', 'python3', 'py']},
 'Java': {'category': 'programming_language', 'aliases': ['java', 'java 8', 'java 11', 'jvm']},
 'C#': {'category': 'programming_language', 'aliases': ['c#', 'csharp', 'c sharp']},
 'C++': {'category': 'programming_language', 'aliases': ['c++', 'cplusplus', 'c plus plus']},
 'Go': {'category': 'programming_language', 'aliases': ['go', 'golang']},
 'Rust': {'category': 'programming_language', 'aliases': ['rust']},
 'TypeScript': {'category': 'programming_language', 'aliases': ['typescript', 'ts', 'type script']},
 'JavaScript': {'category': 'programming_language', 'aliases': ['javascript', 'js', 'java script']},
 'SQL': {'category': 'query_language', 'aliases': ['sql']},
 'Kotlin': {'category': 'programming_language', 'aliases': ['kotlin']},
 'Swift': {'category': 'programming_language', 'aliases': ['swift']},
 'Bash': {'category': 'scripting_language', 'aliases': ['bash']},
 'Django': {'category': 'backend_framework', 'aliases': ['django']},
 'FastAPI': {'category': 'backend_framework', 'aliases': ['fastapi', 'fast api', 'fast-api']},
 'Flask': {'category': 'backend_framework', 'aliases': ['flask']},
 'Spring Boot': {'category': 'backend_framework', 'aliases': ['spring boot', 'springboot']},
 'ASP.NET Core': {'category': 'backend_framework', 'aliases': ['asp.net core', 'aspnet core', 'aspnetcore']},
 'Express.js': {'category': 'backend_framework', 'aliases': ['express', 'expressjs', 'express.js']},
 'NestJS': {'category': 'backend_framework', 'aliases': ['nestjs', 'nest js']},
 'Ruby on Rails': {'category': 'backend_framework', 'aliases': ['rails', 'ruby on rails']},
 'Laravel': {'category': 'backend_framework', 'aliases': ['laravel']},
 'Node.js': {'category': 'backend_runtime', 'aliases': ['node', 'nodejs', 'node.js']},
 'React': {'category': 'frontend_framework', 'aliases': ['react', 'reactjs', 'react.js']},
 'Angular': {'category': 'frontend_framework', 'aliases': ['angular', 'angularjs', 'angular js']},
 'Vue.js': {'category': 'frontend_framework', 'aliases': ['vue', 'vuejs', 'vue.js']},
 'Svelte': {'category': 'frontend_framework', 'aliases': ['svelte']},
 'Next.js': {'category': 'frontend_framework', 'aliases': ['nextjs', 'next.js']},
 'HTML': {'category': 'markup_language', 'aliases': ['html']},
 'CSS': {'category': 'style_language', 'aliases': ['css']},
 'Tailwind CSS': {'category': 'style_language', 'aliases': ['tailwind', 'tailwind css']},
 'Android SDK': {'category': 'mobile', 'aliases': ['android sdk', 'android']},
 'iOS SDK': {'category': 'mobile', 'aliases': ['ios sdk', 'ios']},
 'React Native': {'category': 'mobile_framework', 'aliases': ['react native']},
 'Flutter': {'category': 'mobile_framework', 'aliases': ['flutter']},
 'PostgreSQL': {'category': 'database', 'aliases': ['postgres', 'postgresql']},
 'MySQL': {'category': 'database', 'aliases': ['mysql', 'my sql']},
 'SQLite': {'category': 'database', 'aliases': ['sqlite']},
 'MongoDB': {'category': 'database', 'aliases': ['mongodb', 'mongo db', 'mongo']},
 'Redis': {'category': 'database', 'aliases': ['redis']},
 'Elasticsearch': {'category': 'search', 'aliases': ['elasticsearch', 'elastic search']},
 'Cassandra': {'category': 'database', 'aliases': ['cassandra']},
 'Neo4j': {'category': 'database', 'aliases': ['neo4j', 'neo 4j']},
 'InfluxDB': {'category': 'database', 'aliases': ['influxdb', 'influx db']},
 'Apache Spark': {'category': 'data_engineering', 'aliases': ['spark', 'apache spark']},
 'Airflow': {'category': 'data_engineering', 'aliases': ['airflow']},
 'dbt': {'category': 'data_engineering', 'aliases': ['dbt', 'data build tool']},
 'Kafka': {'category': 'data_engineering', 'aliases': ['kafka']},
 'Parquet': {'category': 'data_engineering', 'aliases': ['parquet']},
 'Avro': {'category': 'data_engineering', 'aliases': ['avro']},
 'Snowflake': {'category': 'data_warehouse', 'aliases': ['snowflake']},
 'BigQuery': {'category': 'data_warehouse', 'aliases': ['bigquery', 'big query', 'bq']},
 'Docker': {'category': 'devops_tool', 'aliases': ['docker']},
 'Kubernetes': {'category': 'devops_tool', 'aliases': ['kubernetes', 'k8s']},
 'Helm': {'category': 'devops_tool', 'aliases': ['helm']},
 'Terraform': {'category': 'devops_tool', 'aliases': ['terraform']},
 'Ansible': {'category': 'devops_tool', 'aliases': ['ansible']},
 'Jenkins': {'category': 'ci_cd_tool', 'aliases': ['jenkins']},
 'GitHub Actions': {'category': 'ci_cd_tool', 'aliases': ['github actions', 'gh actions']},
 'GitLab CI': {'category': 'ci_cd_tool', 'aliases': ['gitlab ci', 'gitlab-ci']},
 'ArgoCD': {'category': 'devops_tool', 'aliases': ['argocd', 'argo cd', 'argo-cd']},
 'Nginx': {'category': 'web_server', 'aliases': ['nginx']},
 'Prometheus': {'category': 'monitoring_logging', 'aliases': ['prometheus']},
 'Grafana': {'category': 'monitoring_logging', 'aliases': ['grafana']},
 'ELK Stack': {'category': 'monitoring_logging', 'aliases': ['elk', 'elk stack']},
 'Vault': {'category': 'security_tool', 'aliases': ['vault', 'hashicorp vault']},
 'AWS': {'category': 'cloud_platform', 'aliases': ['aws', 'amazon web services']},
 'Azure': {'category': 'cloud_platform', 'aliases': ['azure', 'microsoft azure']},
 'Google Cloud': {'category': 'cloud_platform', 'aliases': ['gcp', 'google cloud']},
 'Unit Testing': {'category': 'testing', 'aliases': ['unit testing', 'unit tests']},
 'Integration Testing': {'category': 'testing', 'aliases': ['integration testing', 'integration tests']},
 'End-to-End Testing': {'category': 'testing', 'aliases': ['e2e testing', 'end to end testing', 'end-to-end testing']},
 'PyTest': {'category': 'testing', 'aliases': ['pytest', 'py test']},
 'JUnit': {'category': 'testing', 'aliases': ['junit']},
 'Selenium': {'category': 'testing', 'aliases': ['selenium']},
 'Postman': {'category': 'testing', 'aliases': ['postman']},
 'Swagger/OpenAPI': {'category': 'api_tooling', 'aliases': ['openapi', 'swagger']},
 'OAuth2': {'category': 'security', 'aliases': ['oauth2', 'oauth 2', 'oauth']},
 'JWT': {'category': 'security', 'aliases': ['jwt', 'json web token']},
 'OWASP Top 10': {'category': 'security', 'aliases': ['owasp top 10', 'owasp']},
 'SAST': {'category': 'security', 'aliases': ['sast', 'static application security testing']},
 'DAST': {'category': 'security', 'aliases': ['dast', 'dynamic application security testing']},
 'IAM': {'category': 'security', 'aliases': ['iam', 'identity and access management']},
 'Secrets Management': {'category': 'security', 'aliases': ['secrets management', 'secret management']},
 'Network Security': {'category': 'security', 'aliases': ['network security']},
 'Machine Learning': {'category': 'ml_concept', 'aliases': ['machine learning', 'ml']},
 'NLP': {'category': 'ml_concept', 'aliases': ['nlp', 'natural language processing']},
 'Transformers': {'category': 'ml_concept', 'aliases': ['transformers', 'transformer models']},
 'LLMs': {'category': 'ml_concept', 'aliases': ['llm', 'llms', 'large language models']},
 'scikit-learn': {'category': 'ml_framework', 'aliases': ['scikit-learn', 'sklearn']},
 'PyTorch': {'category': 'ml_framework', 'aliases': ['pytorch', 'py torch']},
 'TensorFlow': {'category': 'ml_framework', 'aliases': ['tensorflow', 'tf']},
 'Keras': {'category': 'ml_framework', 'aliases': ['keras']},
 'Hugging Face': {'category': 'ml_framework', 'aliases': ['hugging face', 'huggingface']},
 'MLflow': {'category': 'ml_framework', 'aliases': ['mlflow', 'ml flow']},
 'MLOps': {'category': 'ml_concept', 'aliases': ['mlops', 'ml ops']},
 'Pandas': {'category': 'ml_library', 'aliases': ['pandas', 'pd']},
 'NumPy': {'category': 'ml_library', 'aliases': ['numpy', 'np']},
 'Git': {'category': 'version_control', 'aliases': ['git']},
 'GitHub': {'category': 'collaboration_tool', 'aliases': ['github', 'git hub']},
 'Jira': {'category': 'project_management', 'aliases': ['jira']},
 'Confluence': {'category': 'collaboration_tool', 'aliases': ['confluence']},
 'Agile': {'category': 'methodology', 'aliases': ['agile']},
 'Scrum': {'category': 'methodology', 'aliases': ['scrum']},
 'REST APIs': {'category': 'architecture', 'aliases': ['rest api', 'rest apis', 'restful api']},
 'GraphQL': {'category': 'architecture', 'aliases': ['graphql']},
 'gRPC': {'category': 'architecture', 'aliases': ['grpc']},
 'Microservices': {'category': 'systems_design', 'aliases': ['microservices', 'microservice']},
 'Distributed Systems': {'category': 'systems_design', 'aliases': ['distributed systems', 'distributed system']},
 'Load Balancing': {'category': 'infrastructure', 'aliases': ['load balancing', 'load balancer']},
 'Caching': {'category': 'infrastructure', 'aliases': ['caching', 'cache']}}
